import type { Metadata } from "next";
import "./globals.css";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import Link from "next/link";

import "@/storyblok";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className="bg-blue-50">
          <header className="bg-[#000000] p-4 sticky top-0 z-[999999]">
            <div className="container mx-auto ">
              <nav className="flex justify-center items-center gap-20">
                <Link
                  className="hover:bg-blue-500 text-white p-2 rounded-md"
                  href={"/"}
                >
                  Home
                </Link>
                <Link
                  className="hover:bg-blue-500 text-white p-2 rounded-md"
                  href={"/tours"}
                >
                  Tours
                </Link>
              </nav>
            </div>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
